### ISSUE TITLE
unmaintained dep "surge"

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/plugin-surge-preview#13]
https://github.com/sintaxi/surge looks unmaintained

**Comment by pat-s** [comment]
Is there an alternative? Do we even want to continue this plugin if the underlying base is unmaintained? We risk introducing CVEs to users potentially.

**Comment by pat-s** [comment]
If the main purpose of the plugin is for PR preview of websites, there are many alternatives: using gh-pages, using S3 buckets, using codeberg pages.

Lately, there was already a request for a plugin to easily use codeberg-pages (https://codeberg.page/). Maybe there could be one plugin which let's users decide between gh-pages and cb-pages dynamically?

**Comment by pat-s** [comment]
I think for previews nobody cares about the final URL (which is why I also like to use http-only S3 URLs). I agree that it would be great to stay with surge as it (still) works and does it's job, but if the maintenance doesn't continue, we need to find a solution for this at some point (either for security or because it will break at some point).

**Comment by pat-s** [comment]
Speaking of it: https://codeberg.org/Codeberg-CI/examples/pulls/35
