### ISSUE TITLE
Add compatibility with Drone CI

### ISSUE THREAD

**Issue by Adito5393** [woodpecker-ci/plugin-surge-preview#3]
Would you accept a PR that would add compatibility with Drone CI via their env vars?

Following env vars will be added:

- `DRONE_REPO_OWNER` -> `CI_REPO_OWNER`
- `DRONE_REPO_NAME` -> `CI_REPO_NAME` (in Drone `CI_REPO_NAME` is set as `DRONE_REPO_OWNER/DRONE_REPO_NAME` )
- `DRONE_PULL_REQUEST` -> `CI_COMMIT_PULL_REQUEST`

**Comment by anbraten** [comment]
I think it wouldn't hurt to much to add them. I would just not "document" them officially, so we can adjust / remove them later without a warning if needed. 

PS: Is there anything blocking you from migrating to woodpecker or why do you want to use drone in general 😅

**Comment by Adito5393** [comment]
That sounds like a fair deal. I will implement the vars & test what happens when both `CI_REPO_NAME` & `DRONE_REPO_NAME` are set.

As I mentioned in #1, I'm waiting for cron jobs PR woodpecker-ci/woodpecker#934 to be merged. I will keep an eye on Woodpecker and try to contribute whenever possible 😃 

PS: good job on sumarizing the ROADMAP issue woodpecker-ci/woodpecker#869

**Comment by ivictbor** [comment]
I think deprecation warnings for such wariables would be awesome, otherwise users risk to get a chaose in their config (will check some example with old vars, blog posts etc)

Though pretty hard to implement, one thing that comes to mind - simply do full-text search in pipeline files for deprecated vars. Not covers cases when they are used in nested processes but at least something

**Comment by anbraten** [comment]
I thought about adding two types of "linter" feedbacks. One for error and one for warnings. Warnings could be used for deprecations as well.
